### ISSUE TITLE
Issues with flutter_secure_storage, auth0_flutter

### ISSUE THREAD

**Issue by odifis** [idenfy/FlutterSDK#11]
I have a Flutter app using the auth0 authentication service.

Here is my pubspec.yaml : 
```
...
dependencies:
  flutter:
    sdk: flutter

  auth0_flutter: ^1.0.2
  flutter_secure_storage: ^7.0.1
  idenfy_sdk_flutter: ^2.0.7
...

```
If I remove from pubspec.yaml hte package idenfy_sdk_flutter, I can launch my app in the Android emulator.
As soon a I add the package, I'm getting this error when trying to login with auth0 or trying to access to secured sotrage : 

```
I/flutter ( 8960): login error: MissingPluginException(No implementation found for method webAuth#login on channel auth0.com/auth0_flutter/web_auth) - stack: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #2      MethodChannelAuth0FlutterWebAuth.invokeRequest (package:auth0_flutter_platform_interface/src/method_channel_auth0_flutter_web_auth.dart:43:16)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #3      MethodChannelAuth0FlutterWebAuth.login (package:auth0_flutter_platform_interface/src/method_channel_auth0_flutter_web_auth.dart:21:9)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #4      WebAuthentication.login (package:auth0_flutter/src/web_authentication.dart:61:25)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #5      _MyHomePageState.loginAction (package:mobileapp/main.dart:131:24)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): 

```

```

E/flutter ( 8796): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
E/flutter ( 8796): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter ( 8796): <asynchronous suspension>
E/flutter ( 8796): #1      _MyHomePageState.loginAction (package:mobileapp/main.dart:119:40)
E/flutter ( 8796): <asynchronous suspension>
E/flutter ( 8796): 
```

Any idea why ?

Thank you ! 

P.S. : I tried to flutter clean, kill and restart the emulator, but still the same pb.

**Comment by viktasidenfy** [comment]
Firstly, we suggest you to test it on a sample project, to see if the problem is in the packages or the project itself. We tried adding flutter_secure_storage to our sample project and it seems to work fine.

**Comment by odifis** [comment]
Thank for your fast answer,

I'm testing with a very simple Project. You're right, there is no problem with idenfy_sdk_flutter + flutter_secure_storage, but as soon we add auth0_flutter, I'm getting MissingPluginException exceptions on different libraries.
So idenfy_sdk_flutter + flutter_secure_storage is working fine ; idenfy_sdk_flutter + auth0_flutter is failing on the methods of auth0_flutter (for eg requesting for the login) ; idenfy_sdk_flutter + flutter_secure_storage + auth0_flutter id failing (for eg reading the secured storage).

Thank you !

**Comment by odifis** [comment]
Hello @viktasidenfy.

Sorry, but I still have this problem and didn't find a way to fix it.
If I'm using auth0_flutter alone, I have no problem. If I'm using idenfy_sdk_flutter, I have no problem.
But using both of it with a very simple example calling the login of auth0 when clicking on a button is failing whn debugging on android.

```
I/flutter ( 8960): login error: MissingPluginException(No implementation found for method webAuth#login on channel auth0.com/auth0_flutter/web_auth) - stack: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #2      MethodChannelAuth0FlutterWebAuth.invokeRequest (package:auth0_flutter_platform_interface/src/method_channel_auth0_flutter_web_auth.dart:43:16)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #3      MethodChannelAuth0FlutterWebAuth.login (package:auth0_flutter_platform_interface/src/method_channel_auth0_flutter_web_auth.dart:21:9)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #4      WebAuthentication.login (package:auth0_flutter/src/web_authentication.dart:61:25)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): #5      _MyHomePageState.loginAction (package:mobileapp/main.dart:131:24)
I/flutter ( 8960): <asynchronous suspension>
I/flutter ( 8960): 
```

I tried to flutter clean, invalidate caches, kill and restart the emulator, but nothing change...

Here is the output of flutter doctor -v  : 
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/nico/.flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nico/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.1)
    • VS Code at /Users/nico/Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 12 (API 31) (emulator)
    • iPhone 11 (mobile)           • 2CFA6B7A-C541-4719-A55B-A93B30F9027C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7
      (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by viktasidenfy** [comment]
Hi, 
We will look into it tomorrow and try to make some changes on our plugin's MethodChannels, maybe it will help. But we cannot make any promises, since the problem might be not on our side.

**Comment by viktasidenfy** [comment]
@odifis So we have added auth0_flutter to our sample project, appended this sample code:

```
  Credentials? _credentials;
  late Auth0 auth0;

  Future<void> initIdenfySdk() async {
    auth0 = Auth0('ourDomain', 'ourClientId');

    final credentials =
    await auth0.webAuthentication().login();

    setState(() {
      _credentials = credentials;
    });

    IdenfyIdentificationResult? idenfySDKresult;
    Exception? localException;
    try {
      String authToken = await getAuthTokenRequest();
      idenfySDKresult = await IdenfySdkFlutter.start(authToken);
    } on Exception catch (e) {
      localException = e;
    }

    setState(() {
      _idenfySDKresult = idenfySDKresult;
      exception = localException;
    });
  }
```

Tried to run our application and call the `initIdenfySdk` function. The login method successfully redirected to the login page. Not sure where is the problem. We tried running on API 33 simulator and API 31 real Android device. Both are working fine.

Our machine is an Intel Core i7 Macbook Pro:

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/viktasjuskys/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/viktasjuskys/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode 14.1.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • M2102J20SG (mobile)          • 43cb69ca      • android-arm64  • Android 12 (API 31)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
The only error we encountered was by closing the opened browser:

```
E/flutter (23963): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: a0.authentication_canceled: The user closed the browser app and the authentication was canceled.
E/flutter (23963): #0      MethodChannelAuth0FlutterWebAuth.invokeRequest (package:auth0_flutter_platform_interface/src/method_channel_auth0_flutter_web_auth.dart:45:7)
E/flutter (23963): <asynchronous suspension>
E/flutter (23963): #1      MethodChannelAuth0FlutterWebAuth.login (package:auth0_flutter_platform_interface/src/method_channel_auth0_flutter_web_auth.dart:21:9)
E/flutter (23963): <asynchronous suspension>
E/flutter (23963): #2      WebAuthentication.login (package:auth0_flutter/src/web_authentication.dart:61:25)
E/flutter (23963): <asynchronous suspension>
E/flutter (23963): #3      _MyAppState.initIdenfySdk (package:idenfy_sdk_flutter_example/main.dart:58:5)
E/flutter (23963): <asynchronous suspension>
```

But, to our understanding, it's because we are missing the implementation code of this cancellation process.

**Comment by odifis** [comment]
@viktasidenfy,

thank you for your fast answer.
Actually, the same modification in your example project is working for me also.

So, I identified the problem. My project was using build:gradle:7.1.2 (This is the default version used when creating a new flutter project with my android studio)
The plugin identify_sdk_flutter is failing with this version of gradle (the compilation is successful but next we're getting these MethodChannel errors). It seems that at least a version 7.2 is required.

Setting the version 7.2.2 is fixing the problem.

So here is my fix in android/build.gradle :
```
    dependencies {
       ...
        classpath 'com.android.tools.build:gradle:7.2.2'
       ...
    } 
```

Maybe it would be worth to add these info in the readme ?

Thank you !
